-- Stored extension: entity sets, finite Status, mappings and membership relation.
CREATE TABLE users (id bigint PRIMARY KEY, display_name text NOT NULL);
CREATE TABLE projects (id bigint PRIMARY KEY, name text NOT NULL);
CREATE TABLE statuses (name text PRIMARY KEY CHECK (name IN ('open', 'closed')));
INSERT INTO statuses VALUES ('open'), ('closed');
CREATE TABLE project_members (
  project_id bigint REFERENCES projects(id),
  user_id bigint REFERENCES users(id),
  PRIMARY KEY (project_id, user_id)
);
CREATE TABLE tasks (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  title text NOT NULL CHECK (length(btrim(title)) BETWEEN 1 AND 200),
  project_id bigint NOT NULL REFERENCES projects(id),
  status text NOT NULL REFERENCES statuses(name),
  created_by bigint NOT NULL,
  created_at timestamptz NOT NULL,
  assignee_id bigint,
  closed_at timestamptz,
  version bigint NOT NULL DEFAULT 0 CHECK (version >= 0),
  FOREIGN KEY (project_id, created_by) REFERENCES project_members(project_id, user_id),
  FOREIGN KEY (project_id, assignee_id) REFERENCES project_members(project_id, user_id),
  CHECK ((status = 'open' AND closed_at IS NULL) OR
         (status = 'closed' AND closed_at IS NOT NULL))
);
CREATE INDEX tasks_project_status ON tasks(project_id, status);
CREATE INDEX tasks_assignee_status ON tasks(assignee_id, status);
